import { requireAuth } from "@/lib/auth"
import { queryOne, query } from "@/lib/db"
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card"
import { Box, Key, Activity, Clock, ShieldCheck, AlertCircle } from "lucide-react"
import { cn } from "@/lib/utils"

export default async function DashboardPage() {
  const user = await requireAuth()

  
  const appCount = await queryOne<{ count: number }>(
    "SELECT COUNT(*) as count FROM application_members WHERE user_id = ?",
    [user.id],
  )

  
  const licenseCount = await queryOne<{ count: number }>(
    "SELECT COUNT(*) as count FROM licenses l JOIN application_members au ON l.application_id = au.application_id WHERE au.user_id = ?",
    [user.id],
  )

  
  const recentLicenses = await query(
    `SELECT l.*, a.name as app_name 
     FROM licenses l 
     JOIN applications a ON l.application_id = a.id 
     JOIN application_members au ON a.id = au.application_id 
     WHERE au.user_id = ? 
     ORDER BY l.created_at DESC LIMIT 5`,
    [user.id],
  )

  return (
    <div className="space-y-8">
      <div>
        <h1 className="text-3xl font-bold tracking-tight">Overview</h1>
        <p className="text-muted-foreground mt-1">Welcome back, {user.name}. Here's what's happening.</p>
      </div>

      {/* Stats Row */}
      <div className="grid gap-4 md:grid-cols-3">
        <Card>
          <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
            <CardTitle className="text-sm font-medium">Total Applications</CardTitle>
            <Box className="h-4 w-4 text-muted-foreground" />
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold">{appCount?.count || 0}</div>
            <p className="text-xs text-muted-foreground">Projects you own or manage</p>
          </CardContent>
        </Card>
        
        <Card>
          <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
            <CardTitle className="text-sm font-medium">Total Licenses</CardTitle>
            <Key className="h-4 w-4 text-muted-foreground" />
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold">{licenseCount?.count || 0}</div>
            <p className="text-xs text-muted-foreground">Keys generated across all apps</p>
          </CardContent>
        </Card>
        
        <Card>
          <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
            <CardTitle className="text-sm font-medium">System Status</CardTitle>
            <Activity className="h-4 w-4 text-emerald-500" />
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold text-emerald-500">Online</div>
            <p className="text-xs text-muted-foreground">All systems normal</p>
          </CardContent>
        </Card>
      </div>

      {/* Recent Licenses Section */}
      <Card className="col-span-4">
        <CardHeader>
          <CardTitle>Recent Activity</CardTitle>
          <CardDescription>The latest license keys generated by you or your team.</CardDescription>
        </CardHeader>
        <CardContent>
          <div className="space-y-4">
            {recentLicenses.map((license: any) => {
              
              const isExpired = license.expires_at && new Date(license.expires_at) < new Date()
              const isUnused = !license.activated_at
              
              let statusText = "Active"
              let statusColor = "bg-emerald-500/10 text-emerald-600 border-emerald-200"
              let Icon = ShieldCheck

              if (!license.is_active) {
                statusText = "Revoked"
                statusColor = "bg-destructive/10 text-destructive border-destructive/20"
                Icon = AlertCircle
              } else if (isExpired) {
                statusText = "Expired"
                statusColor = "bg-orange-500/10 text-orange-600 border-orange-200"
                Icon = Clock
              } else if (isUnused) {
                statusText = "Unused"
                statusColor = "bg-blue-500/10 text-blue-600 border-blue-200"
                Icon = Clock
              }

              return (
                <div key={license.id} className="flex items-center justify-between p-4 border rounded-xl hover:bg-muted/40 transition-all">
                  <div className="flex items-center gap-4">
                    {/* Icon Box */}
                    <div className={cn("p-2 rounded-lg", statusColor.split(' ')[0])}>
                      <Icon className={cn("h-5 w-5", statusColor.split(' ')[1])} />
                    </div>
                    
                    <div className="space-y-1">
                      <div className="flex items-center gap-2">
                        <span className="font-mono font-medium text-sm text-foreground/90">
                          {license.license_key}
                        </span>
                        <span className={cn("text-[10px] px-2 py-0.5 rounded-full border font-medium uppercase tracking-wide", statusColor)}>
                          {statusText}
                        </span>
                      </div>
                      <div className="flex items-center gap-2 text-xs text-muted-foreground">
                        <span className="font-medium text-foreground/70">{license.app_name}</span>
                        <span>•</span>
                        {isUnused 
                          ? <span>Duration: {license.duration_days} days (Starts on use)</span>
                          : <span>Expires: {new Date(license.expires_at).toLocaleDateString()}</span>
                        }
                      </div>
                    </div>
                  </div>
                  
                  <div className="text-xs text-muted-foreground text-right hidden sm:block">
                    <div>Created</div>
                    <div>{new Date(license.created_at).toLocaleDateString()}</div>
                  </div>
                </div>
              )
            })}
            
            {recentLicenses.length === 0 && (
              <div className="flex flex-col items-center justify-center py-12 text-center border-2 border-dashed rounded-xl bg-muted/20">
                <Key className="h-10 w-10 text-muted-foreground/50 mb-3" />
                <h3 className="font-medium text-lg">No licenses yet</h3>
                <p className="text-muted-foreground text-sm max-w-sm">
                  Create your first application and generate a license key to see it appear here.
                </p>
              </div>
            )}
          </div>
        </CardContent>
      </Card>
    </div>
  )
}